remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: "Team 7 Project Github Page"
description: "Welcome to our amazing team 7 Github page. Enjoy our amazing code."
gitorg: "https://github.com/jm1021/leuck_reunion"
description: "June 26 to July 1 2023"
google_analytics:
